#on: push
#name: ðŸš€ Deploy website on push
#jobs:
#  web-deploy:
#    name: ðŸŽ‰ Deploy
#    runs-on: ubuntu-latest
#    steps:
#    - name: ðŸšš Get latest code
#      uses: actions/checkout@v4
#    
#    - name: ðŸ“‚ Sync files
#      uses: SamKirkland/FTP-Deploy-Action@v4.1.0
#      with:
#        server: grh44.myukcloud.com
#        username: k3-fDdePstOO0@rt.fitness
#        password: ${{ secrets.FTPPASSWORD }}
#        protocol: ftps
#        server-dir: public_html/wp-content/themes/rt-fitness/